Repository ipdk-io/stratum-dev, pull requests merged in 2023-11, with the labels that each got.

#151 Update workflow to exclude flaky unit tests
  .github/workflows/pipeline.yml
  bazel/rules/test_rule.bzl
  stratum/hal/lib/common/BUILD
Labels: trivial effort, bazel

#153 Run clang-format on stratum source
  stratum/hal/bin/tdi/tdi_pipeline_builder.cc
Labels: trivial effort

#149 P4CP PacketIO support
  stratum/hal/bin/tdi/tdi_pipeline_builder.cc
  stratum/hal/lib/tdi/es2k/BUILD
  stratum/hal/lib/tdi/es2k/CMakeLists.txt
  stratum/hal/lib/tdi/es2k/es2k_sde_packetio.cc
  stratum/hal/lib/tdi/es2k/es2k_sde_wrapper.cc
  stratum/hal/lib/tdi/es2k/es2k_sde_wrapper.h
  stratum/hal/lib/tdi/tdi.proto
  stratum/hal/lib/tdi/tdi_node.cc
  stratum/hal/lib/tdi/tdi_sde_interface.h
  stratum/hal/lib/tdi/tdi_sde_mock.h
  stratum/hal/lib/tdi/tdi_sde_wrapper.cc
  stratum/hal/lib/tdi/tdi_sde_wrapper.h
Labels: major effort

#150 Added support for Indirect PacketModMeter in stratum layer
  stratum/hal/bin/tdi/es2k/BUILD
  stratum/hal/lib/p4/p4_info_manager.cc
  stratum/hal/lib/p4/p4_info_manager.h
  stratum/hal/lib/p4/p4_info_manager_mock.h
  stratum/hal/lib/tdi/es2k/BUILD
  stratum/hal/lib/tdi/es2k/CMakeLists.txt
  stratum/hal/lib/tdi/es2k/es2k_sde_meter.cc
  stratum/hal/lib/tdi/es2k/es2k_sde_table_data.cc
  stratum/hal/lib/tdi/es2k/es2k_sde_wrapper.h
  stratum/hal/lib/tdi/tdi_constants.h
  stratum/hal/lib/tdi/tdi_pkt_mod_meter_config.h
  stratum/hal/lib/tdi/tdi_sde_interface.h
  stratum/hal/lib/tdi/tdi_sde_mock.h
  stratum/hal/lib/tdi/tdi_sde_wrapper.h
  stratum/hal/lib/tdi/tdi_table_manager.cc
Labels: major effort

#158 Enable Dependabot scanning
  .github/dependabot.yml
Labels: trivial effort, github_actions

#159 Add clang-format check
  .github/workflows/clang-format-check.yml
  stratum/hal/lib/yang/yang_parse_tree_ipsec.cc
Labels: minor effort, github_actions

#160 Address compiler warnings
  stratum/hal/lib/p4/p4_info_manager.cc
  stratum/hal/lib/tdi/tdi_table_manager.cc
Labels: bug, trivial effort

#161 Fix errors in mock classes
  stratum/hal/lib/p4/p4_info_manager_mock.h
  stratum/hal/lib/tdi/tdi_sde_mock.h
  stratum/hal/lib/tdi/tdi_sde_wrapper.h
Labels: bug, trivial effort
