Repository ipdk-io/stratum-dev, pull requests merged in 2023-10, with the labels that each got.

#138 Downstream changes to init_google.h
  stratum/glue/init_google.h
Labels: minor effort, downstreaming

#144 Move OpenSSL dependency
  CMakeLists.txt
  stratum/hal/lib/tdi/CMakeLists.txt
Labels: trivial effort, cmake

#143 Remove redundant cmake commands
  CMakeLists.txt
Labels: trivial effort, cmake

#140 Eliminate legacy bytestring responses flag
  stratum/hal/lib/tdi/BUILD
  stratum/hal/lib/tdi/CMakeLists.txt
  stratum/hal/lib/tdi/tdi_packetio_manager.cc
  stratum/hal/lib/tdi/tdi_sde_flags.cc
  stratum/hal/lib/tdi/tdi_sde_flags.h
  stratum/hal/lib/tdi/tdi_sde_table_data.cc
  stratum/hal/lib/tdi/tdi_sde_table_key.cc
Labels: minor effort, downstreaming

#142 Normalize stratum/hal/lib/tdi/macros.h
  stratum/hal/lib/tdi/BUILD
  stratum/hal/lib/tdi/CMakeLists.txt
  stratum/hal/lib/tdi/dpdk/BUILD
  stratum/hal/lib/tdi/dpdk/dpdk_port_manager.cc
  stratum/hal/lib/tdi/dpdk/dpdk_sde_target.cc
  stratum/hal/lib/tdi/es2k/BUILD
  stratum/hal/lib/tdi/es2k/es2k_port_manager.cc
  stratum/hal/lib/tdi/es2k/es2k_port_manager_dummy.cc
  stratum/hal/lib/tdi/es2k/es2k_sde_table_data.cc
  stratum/hal/lib/tdi/es2k/es2k_sde_target.cc
  stratum/hal/lib/tdi/tdi_bf_status.h
  stratum/hal/lib/tdi/tdi_id_mapper.cc
  stratum/hal/lib/tdi/tdi_sde_action_profile.cc
  stratum/hal/lib/tdi/tdi_sde_clone_session.cc
  stratum/hal/lib/tdi/tdi_sde_counter.cc
  stratum/hal/lib/tdi/tdi_sde_meter.cc
  stratum/hal/lib/tdi/tdi_sde_multicast.cc
  stratum/hal/lib/tdi/tdi_sde_register.cc
  stratum/hal/lib/tdi/tdi_sde_table_data.cc
  stratum/hal/lib/tdi/tdi_sde_table_entry.cc
  stratum/hal/lib/tdi/tdi_sde_table_key.cc
  stratum/hal/lib/tdi/tdi_sde_wrapper.cc
  stratum/hal/lib/tdi/tdi_sde_wrapper.h
  stratum/hal/lib/tdi/tofino/BUILD
  stratum/hal/lib/tdi/tofino/tofino_port_manager.cc
  stratum/hal/lib/tdi/tofino/tofino_sde_target.cc
Labels: medium effort, bazel

#146 Fix tdi_pipeline_builder compile errors with gRPC v1.59.1
  stratum/hal/bin/tdi/tdi_pipeline_builder.cc
Labels: trivial effort

#139 Merge license and documentation updates
  .reuse/dep5
  CONTRIBUTING.md
  LICENSES/CC0-1.0.txt
  NOTICE
  README.md
  legal/BUILD
  legal/LICENSE.bcm-opennsa.txt
  legal/LICENSE.bcm-sdklt.txt
  legal/LICENSE.intel-sde.txt
  legal/NOTICE.bmv2.txt
  legal/NOTICE.common.txt
  legal/NOTICE.intel-sde.txt
  legal/NOTICE.json.txt
  legal/NOTICE.opennsa.txt
  legal/NOTICE.p4c.txt
  legal/NOTICE.pi.txt
  legal/NOTICE.sdklt.txt
  legal/NOTICE.yaml.txt
  stratum/docs/logging_guide.md
  stratum/docs/setup_guide_barefoot_tofino_onos.md
Labels: minor effort, downstreaming

#147 Revert "Eliminate legacy bytestring responses flag"
  stratum/hal/lib/tdi/BUILD
  stratum/hal/lib/tdi/CMakeLists.txt
  stratum/hal/lib/tdi/tdi_packetio_manager.cc
  stratum/hal/lib/tdi/tdi_sde_flags.cc
  stratum/hal/lib/tdi/tdi_sde_flags.h
  stratum/hal/lib/tdi/tdi_sde_table_data.cc
  stratum/hal/lib/tdi/tdi_sde_table_key.cc
Labels: bug, minor effort

#148 Implement Stratum CI pipeline
  .github/dpdk-tests.txt
  .github/workflows/pipeline.yml
Labels: medium effort
